import { AuthProvider } from '@/contexts/AuthContext';
import '../../styles/globals.scss';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: 'SujeitoPizzaria',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
       <AuthProvider>
          <ToastContainer autoClose={3000} />
          {children}
       </AuthProvider>
      </body>
    </html>
  )
}
